<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <ShinyVersion>4.0.1</ShinyVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Microsoft.Maui.Controls" Version="$(MauiVersion)"/>
        <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.3"/>
        <PackageVersion Include="Nerdbank.GitVersioning" Version="3.9.50"/>
        <PackageVersion Include="BenchmarkDotNet" Version="0.15.8"/>
        <PackageVersion Include="Shouldly" Version="4.3.0"/>
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.3.0"/>
        <PackageVersion Include="xunit" Version="2.9.3"/>
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5"/>
        <PackageVersion Include="Shiny.Locations" Version="$(ShinyVersion)"/>
        <PackageVersion Include="Shiny.Notifications" Version="$(ShinyVersion)"/>
        <PackageVersion Include="Shiny.Hosting.Maui" Version="$(ShinyVersion)"/>
    </ItemGroup>
</Project>