<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(BaseTargetFramework)-ios;$(BaseTargetFramework)-android</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <RootNamespace>Sample.Maui</RootNamespace>
        <MauiXamlInflator>SourceGen</MauiXamlInflator>

        <ApplicationTitle>Spatial GPS Sample</ApplicationTitle>
        <ApplicationId>com.shinylib.spatial.sample</ApplicationId>
        <ApplicationVersion>1</ApplicationVersion>
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>

        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">23.0</SupportedOSPlatformVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <CodesignKey>iPhone Developer</CodesignKey>
      <MtouchExtraArgs>-v -v -v -v</MtouchExtraArgs>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Shiny.Spatial.Geofencing\Shiny.Spatial.Geofencing.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Maui.Controls"/>
        <PackageReference Include="Shiny.Locations"/>
        <PackageReference Include="Shiny.Notifications"/>
        <PackageReference Include="Shiny.Hosting.Maui"/>
    </ItemGroup>

    <ItemGroup>
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)"/>
        <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4"/>
        <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128"/>
        <MauiImage Include="Resources\Images\*"/>
        <MauiFont Include="Resources\Fonts\*"/>
    </ItemGroup>

</Project>
