<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
<!--        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)</TargetFrameworks>-->
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)-ios</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)-android</TargetFrameworks>
        
        <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
        <IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsTrimmable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Shiny.Spatial/Shiny.Spatial.csproj"/>
        <PackageReference Include="Shiny.Locations"/>
    </ItemGroup>
</Project>
